- backend/routes/api.php
overview
remove register bawaan laravel
kang @aldidoanta
> remove api default

- frontend/pages/auth/login.vue
overview 
auth-security
@firmanhxc @aldidoanta @sandisunandar99
> auth-security

- backend/app/Http/Controllers/Registrasisampel.php
- backend/app/Http/Controllers/V1/PCRController.php
- backend/app/Http/Controllers/V1/VerifikasiController.php
- frontend/components/global/AjaxTable.vue
overview 
ajaxtable page max 500 entry 
@firmanhxc @aldidoanta
> ajaxtable page

- .codeclimate.yml
- README.md
> init codeclimate

- backend/app/Exceptions/Handler.php
overview
clean code handler exception
cc: @jabardigitalservice/jds-backend
> clean code handler exception

- backend/app/Exceptions/Handler.php
> cleancode-3

- backend/docker-config/nginx.conf
> setup upload max

- frontend/.gitignore
- frontend/README.md
- frontend/sonar-project.properties.example
- setup sonarqube in pikobar labkes satelit
- create frontend/readme.md
cc: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> setup sonarqube

- frontend/components/global/AjaxTable.vue
- frontend/components/global/table-row/TrDataRegisSample.vue
- frontend/components/global/table-row/TrDataTerimaSampel.vue
- frontend/components/global/table-row/TrHasilPemeriksaanAdmin.vue
- frontend/pages/hasil-pemeriksaan/index.vue
- frontend/pages/registrasi-sampel/index.vue
- frontend/pages/registrasi-sampel/terima-sampel.vue
- frontend/store/hasil_pemeriksaan.js
- frontend/store/registrasi_perujuk.js
- frontend/store/registrasi_sampel.js
bugfix registrasi sampel checkbox data popup selected / checked not displayed
(refactor code, sebelumnya hanya menyimpan id, menjadi store id and value)
impact: hasil pemeriksaan dan terima sampel
https://trello.com/c/d8egHaEG/419-308-bug-hapus-list-pasien
cc @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> bugfix registrasi sampel checkbox

- backend/app/Console/Commands/SyncIntegrasiLabkesCommand.php
- backend/app/Models/Labkes/Sampel.php
- backend/app/Models/PemeriksaanSampel.php
add hasil deteksi pada cronjob labkes-satelit
cc @aldidoanta @jabardigitalservice/jds-backend @yoslie
> add hasil deteksi

- backend/app/Http/Controllers/V1/VerifikasiController.php
- backend/app/Models/Sampel.php
overview
bugfix detail sampel
cc: @jabardigitalservice/jds-backend @yoslie
> bugfix detail sampel

- frontend/components/Sidebar.vue
- frontend/pages/auth/login.vue
- frontend/pages/hasil-pemeriksaan/index.vue
improvement halaman hasil pemeriksaan agar bisa dipakai admin dinkes / tampil di index akun admin dinkes
https://trello.com/c/sy362zZy/420-309-akun-dinkes-kab-kota
cc: @ayocodingit @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> improvement halaman hasil pemeriksaan

- backend/database/migrations/2021_02_15_154934_remove_foreign_key_kota_id_on_pasien.php
overview
remove foreignkey pasien kota id
@jabardigitalservice/jds-backend @yoslie
> bugfix remove foreignkey pasien

- frontend/assets/js/constant/enum.js
- frontend/pages/dinkes/edit.vue
- frontend/pages/dinkes/index.vue
- frontend/pages/dinkes/show.vue
- frontend/pages/hasil-pemeriksaan/index.vue
- frontend/pages/user/index.vue
- frontend/utils/index.js
- Bugfix kelola akun lab, daftar lab satelit tidak muncul
- Revision kelola akun dinkes (CRUD), update list dinkes dari list lab menjadi list kota
- minor refactor code on previous [PR](https://github.com/jabardigitalservice/pikobar-labkes-satelit/pull/144) page hasil pemeriksaan(cc: @adrianpdm )
https://trello.com/c/LH9eC0ft/431-315-field-dropdown-laboratorium-tidak-muncul-di-fe
https://trello.com/c/yV9rwkks/432-317-kelola-akun-dinkes-kab-kota
cc: @ayocodingit @adrianpdm @Arif9878 @maruf12 @adzharamrullah
> bugfix kelola akun user dan revision kelola akun dinkes

- frontend/components/global/table-row/TrDinkes.vue
- frontend/components/global/table-row/TrUser.vue
- frontend/pages/dinkes/show.vue
Update response data from api
- response data dinkes name
- response data lab name
cc: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> update response data api

- backend/app/Traits/JoinTrait.php
bugfix dblink
cc: @jabardigitalservice/jds-backend @smilelikeshit @aldidoanta
> bugfix dblink

- frontend/lang/id.json
- frontend/pages/dinkes/edit.vue
- frontend/pages/dinkes/index.vue
- frontend/pages/dinkes/tambah.vue
- frontend/router.js
- wording admin dinkes menjadi nama admin
- memindahkan popup tambah akun menjadi page agar tidak bertabrakan dengan popup error message
https://trello.com/c/yV9rwkks/432-317-kelola-akun-dinkes-kab-kota
CC: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> revision and fix minor bug on kelola akun dinkes

- frontend/assets/js/constant/enum.js
- frontend/components/Sidebar.vue
- frontend/components/global/table-row/TrPerujuk.vue
- frontend/lang/id.json
- frontend/pages/perujuk/edit.vue
- frontend/pages/perujuk/index.vue
- frontend/pages/perujuk/show.vue
- frontend/pages/perujuk/tambah.vue
- frontend/router.js
add feature kelola akun perujuk (crud)
https://trello.com/c/sw9CXKel/355-311-kelola-akun-perujuk-sampel
CC: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> add feature kelola akun perujuk

- frontend/pages/dinkes/tambah.vue
minor wording name in heding section kelola akun dinkes (add)
cc: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank @ayocodingit
> minor wording name

- backend/app/Models/PemeriksaanSampel.php
bugfix command integrasi labkes kesimpulan pemeriksaan
cc: @jabardigitalservice/jds-backend @aldidoanta
> tranform swab_ulang dan sampel kurang -> invalid

- frontend/components/global/table-row/TrPerujuk.vue
- frontend/pages/perujuk/edit.vue
- frontend/pages/perujuk/index.vue
- frontend/pages/perujuk/tambah.vue
- bugfix gagal edit data
- update struktur table menambah kolom 'terakhir login'
- fix sorting table function only apply for sorting email
https://trello.com/c/VKJy6GrR/436-319-data-master-instansi-pengirim
cc @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank
> bugfix kelola akun perujuk

- backend/app/Enums/KriteriaEnum.php
- backend/app/Enums/RoleEnum.php
- backend/app/Http/Controllers/V1/ImportRegisterController.php
- backend/app/Http/Requests/ImportValidationRequest.php
- backend/app/Imports/RegisterPerujukImport.php
- backend/app/Models/RegisterPerujuk.php
- backend/app/Rules/ExcelExtensionRule.php
- backend/app/Traits/FilterTrait.php
- backend/app/Traits/OrderTrait.php
- backend/app/Traits/RegisterPerujukTrait.php
- backend/resources/lang/en/validation.php
- backend/resources/lang/id/validation.php
bugfix validation import excel
enum kriteria
remove return query when
cc: @jabardigitalservice/jds-backend @aldidoanta
> Bugfix validation excel import

- backend/app/Http/Requests/RegisterPerujukRequest.php
- backend/app/Models/JenisSampel.php
- backend/app/Models/Negara.php
data master jenis sampel dan negara connect ke labkes 
cc: @aldidoanta @jabardigitalservice/jds-backend
> data master connect labkes

- frontend/components/global/AjaxTable.vue
> ajaxtable response paginate

- .codeclimate.yml
- backend/app/Http/Controllers/V1/ImportRegisterController.php
- backend/app/Http/Controllers/V1/RegisterPerujukController.php
- backend/app/Imports/RegisterPerujukImport.php
- backend/app/Imports/RegisterSampelImport.php
- backend/app/Models/Register.php
- backend/app/Models/RegisterPerujuk.php
- backend/app/Models/Sampel.php
- backend/app/Rules/UniqueSampelPerujuk.php
- backend/app/Traits/RegisterPerujukTrait.php
- backend/resources/lang/vendor/enum/en/validation.php
- backend/resources/lang/vendor/enum/id/validation.php
update import register sampel
update minor import register perujuk
cc: @jabardigitalservice/jds-backend @aldidoanta @rizkyrmsyah
> Import register sampel

- frontend/pages/perujuk/edit.vue
- frontend/pages/perujuk/tambah.vue
sub task pengerjaan [update instansi pengirim](https://github.com/jabardigitalservice/pikobar-labkes-satelit/pull/168)
- update opsi instansi pengirim pada kelola akun perujuk (form add, form edit)
- update error conditional (form add, form edit)
- minor refactor style class
https://github.com/jabardigitalservice/pikobar-labkes-satelit/pull/168
https://trello.com/c/B0xKW1vs/447-328-update-form-registrasi-sampel
cc: @adrianpdm @Arif9878 @maruf12 @adzharamrullah @naufalihsank @maulanayuseph @bangunbagustapa @Ibwedagama
> revision kelola akun perujuk
